apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-java
  template:
    metadata:
      labels:
        app: rest-java
    spec:
      containers:
      - name: java
        image: maho/rest-java:1.0
        imagePullPolicy: Always
        env:
        - name: DATABASE
          value: postgres-spring
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DATABASE
          value: demodb
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          failureThreshold: 5
