apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-java
  template:
    metadata:
      labels:
        app: rest-java
    spec:
      containers:
      - name: java
        image: maho/rest-java:0.1
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 130
          timeoutSeconds: 10
          failureThreshold: 10
